using System;
using System.Collections.Generic;
using UnityEngine;

namespace CubeChallenge3D.Core
{
    public enum AppLanguage
    {
        English,
        Korean
    }

    public sealed class LocalizationManager : MonoBehaviour
    {
        public static LocalizationManager Instance { get; private set; }

        public AppLanguage CurrentLanguage { get; private set; } = AppLanguage.English;

        private readonly Dictionary<AppLanguage, Dictionary<string, string>> localizedText = new()
        {
            {
                AppLanguage.English,
                new Dictionary<string, string>
                {
                    { "play", "Play" },
                    { "quick_play", "Practice" },
                    { "practice", "Practice" },
                    { "ranking_challenge", "Ranking Challenge" },
                    { "stages", "Stages" },
                    { "target", "Target" },
                    { "solver", "Solver" },
                    { "solver_learn", "Solver & Learn" },
                    { "records", "World Records" },
                    { "shop", "Shop" },
                    { "rewards", "Rewards" },
                    { "coins", "Coins" },
                    { "gems", "Gems" },
                    { "buy", "Buy" },
                    { "owned", "Owned" },
                    { "not_enough_coins", "Not enough coins" },
                    { "daily_reward", "Daily Reward" },
                    { "claim", "Claim" },
                    { "claimed", "Claimed" },
                    { "milestone_reward", "Milestone Reward" },
                    { "watch_ad_for_coins", "Watch Ad for Coins" },
                    { "premium_skins_coming_soon", "Premium cube skins coming soon" },
                    { "ranking", "Ranking" },
                    { "settings", "Settings" },
                    { "back", "Back" },
                    { "home", "Home" },
                    { "retry", "Retry" },
                    { "new_game", "New Game" },
                    { "reset", "Reset" },
                    { "time", "Time" },
                    { "moves", "Moves" },
                    { "continue", "Continue" },
                    { "hint", "Hint" },
                    { "view", "View" },
                    { "solve", "Solve" },
                    { "drag", "Drag" },
                    { "keypad", "Keypad" },
                    { "undo", "Undo" },
                    { "help", "Help" },
                    { "close", "Close" },
                    { "show_debug", "Show Debug Panel" },
                    { "sound", "Sound" },
                    { "vibration", "Vibration" },
                    { "push_notifications", "Push Notifications" },
                    { "language", "Language" },
                    { "english", "English" },
                    { "korea", "Korea" },
                    { "coming_soon", "Coming Soon" },
                    { "solve_stage", "Solve Stage" },
                    { "reverse_target_stage", "Reverse Target Stage" },
                    { "locked", "Locked" },
                    { "cleared", "Cleared" },
                    { "stars", "Stars" },
                    { "difficulty", "Difficulty" },
                    { "move_limit", "Move Limit" },
                    { "not_playable_yet", "Not playable yet" },
                    { "stage_clear", "Stage Clear!" },
                    { "stage_failed", "Out of moves" },
                    { "remaining_moves", "Remaining Moves" },
                    { "next_stage", "Next Stage" },
                    { "stage_list", "Stage List" },
                    { "best_moves", "Best Moves" },
                    { "best_time", "Best Time" },
                    { "star_conditions_title", "Star Conditions" },
                    { "star_title_count", "{0} Stars" },
                    { "star_title_one", "1 Star" },
                    { "star_condition_3", "Within {0} moves\nNo help items used" },
                    { "star_condition_2", "Within {0} moves\nOr after using 1-2 help items" },
                    { "star_condition_1", "Clear within {0} moves\nOr after additional help item penalties" },
                    { "start", "Start" },
                    { "no_records", "No records yet." },
                    { "purchased", "Purchased." },
                    { "equipped", "Equipped." },
                    { "already_owned", "Already owned." },
                    { "not_enough_gems", "Not enough gems." },
                    { "hearts", "Hearts" },
                    { "uses_one_heart", "Uses 1 Heart" },
                    { "not_enough_hearts", "Not Enough Hearts" },
                    { "hearts_recharge", "Hearts recharge over time." },
                    { "next_heart_in", "Next heart in" },
                    { "get_more_hearts", "Get more hearts in the Shop." },
                    { "no_hearts_required", "No hearts required." },
                    { "go_to_shop", "Go to Shop" },
                    { "reward_claimed", "Reward claimed." },
                    { "reward", "Reward" },
                    { "ad_not_ready", "Ad not ready. Try again later." },
                    { "ad_not_completed", "Ad not completed." },
                    { "ads_unavailable", "Ads are not available yet." },
                    { "profile", "Profile" },
                    { "customize_experience", "Customize your experience" },
                    { "nickname", "Nickname" },
                    { "edit", "Edit" },
                    { "google_play", "Google Play" },
                    { "connected", "Connected" },
                    { "connect", "Connect" },
                    { "not_connected", "Not connected" },
                    { "on", "ON" },
                    { "off", "OFF" },
                    { "change_nickname", "Change Nickname" },
                    { "choose_avatar", "Choose Avatar" },
                    { "nickname_ticket_info", "Uses 1 Nickname Change Ticket\nNickname can only be changed once per day." },
                    { "cancel", "Cancel" },
                    { "ok", "OK" },
                    { "nickname_placeholder", "Nickname" },
                    { "choose_language", "Choose Language" },
                    { "language_changed", "Language changed." },
                    { "create_profile_first", "Create a profile first." },
                    { "google_play_failed", "Google Play sign-in failed. Please try again." },
                    { "google_play_connected", "Google Play connected." },
                    { "avatar_anytime", "Avatar can be changed anytime." },
                    { "avatar_changed", "Avatar changed." },
                    { "avatar_changed_synced", "Avatar changed and synced." },
                    { "avatar_changed_local", "Avatar changed locally. Server sync pending." },
                    { "tickets_available", "Tickets available: {0}" },
                    { "need_nickname_ticket", "You need a Nickname Change Ticket." }
                    ,
                    { "manual_solver", "Manual Solver" },
                    { "learn_basics", "Learn Basics" },
                    { "solver_learn_title", "Solver & Learn" },
                    { "solver_learn_subtitle", "Choose a solver or learning activity." },
                    { "solver_instruction", "Select a color, then enter the stickers." },
                    { "previous", "Previous" },
                    { "next", "Next" },
                    { "validate", "Validate" },
                    { "reset_solved", "Reset Solved" },
                    { "clear", "Clear" },
                    { "save", "Save" },
                    { "load", "Load" },
                    { "play_3d", "Play 3D" },
                    { "debug", "Debug" },
                    { "open", "Open" },
                    { "lessons", "Lessons" },
                    { "lesson", "Lesson" },
                    { "previous_edge", "Previous Edge" },
                    { "next_edge", "Next Edge" },
                    { "previous_case", "Previous Case" },
                    { "next_case", "Next Case" },
                    { "mark_complete", "Mark Complete" },
                    { "play_demo", "Play Demo" },
                    { "back_to_lessons", "Back to Lessons" },
                    { "learn_3d_demo", "Learn 3D Demo" },
                    { "learn_3d_demo_subtitle", "Keep Front, Top, and Right fixed while watching the moves." },
                    { "lesson_completed", "Lesson completed." },
                    { "lesson_unavailable", "Lesson unavailable" },
                    { "lesson_data_unavailable", "Lesson data is unavailable." },
                    { "no_lesson_category", "No lesson category is available." },
                    { "key_points", "Key Points" },
                    { "moves_label", "Moves" },
                    { "demo_type_label", "Demo Type" },
                    { "demo_purpose_label", "Demo Purpose" },
                    { "demo_goal_label", "Demo Goal" },
                    { "target_piece_label", "Target Piece" },
                    { "target_slot_label", "Target Slot" },
                    { "no_3d_demo", "This lesson does not include a 3D demo." },
                    { "no_3d_demo_yet", "This lesson does not include a 3D demo yet." },
                    { "learn_more_later", "More guided cases will be expanded in the next Learn update." },
                    { "target_pattern", "Target Pattern" },
                    { "match_this_cube", "Match this cube." },
                    { "view_target", "View Target" },
                    { "continue_plus_moves", "Continue +{0}" },
                    { "move_plus", "+{0} Move" },
                    { "force_clear", "Force Clear" },
                    { "out_of_moves_ad", "Out of moves\nWatch Ad for +{0} Moves\n{1}/{2} used" },
                    { "daily_rewards_title", "Daily Rewards" },
                    { "daily_rewards_subtitle", "Claim today's reward and get 3 Solver Tickets!" },
                    { "day_label", "Day {0}" },
                    { "solver_tickets", "Solver Tickets" },
                    { "world_records_title", "World Records" },
                    { "world_records_subtitle", "See who has cleared the most stages." },
                    { "rank", "Rank" },
                    { "player", "Player" },
                    { "stage", "Stage" }
                    ,
                    { "tutorial_mode", "Tutorial Mode" },
                    { "normal_mode", "Normal Mode" },
                    { "hard_mode", "Hard Mode" },
                    { "infinity_mode", "Infinity Mode" },
                    { "tutorial_mode_desc", "Clear beginner stages and earn stars." },
                    { "normal_mode_desc", "Clear stages and earn stars." },
                    { "hard_mode_desc", "Match target stages and earn stars." },
                    { "infinity_mode_desc", "Mixed stages with endless-style progression." },
                    { "select_block", "Select Block" },
                    { "choose_block", "Choose a block to inspect." },
                    { "block_rewards", "Block Rewards" },
                    { "block_label", "Block {0}" },
                    { "block_multiline", "Block\n{0}" },
                    { "stages_range", "Stages {0} - {1}" },
                    { "complete_stages_rewards", "Complete stages to earn stars and get amazing rewards!" },
                    { "locked_label", "Locked" },
                    { "solver_learn_hint", "Learn faces, turns, and notation from the Solver & Learn menu." },
                    { "solver_result_not_solved", "Result: Not solved yet." },
                    { "invalid_cube_input", "Invalid cube input" },
                    { "cube_input_valid", "Cube input is valid." },
                    { "status_label", "Status" },
                    { "validation_passed", "Validation passed" },
                    { "ready_to_solve", "Ready to solve" },
                    { "invalid_cube", "Invalid cube" },
                    { "reset_to_solved_cube", "Reset to solved cube." },
                    { "cube_already_solved", "Cube is already solved" },
                    { "solution_label", "Solution" },
                    { "no_moves_needed", "No moves needed" },
                    { "input_cleared", "Input cleared." },
                    { "solver_input_saved", "Solver input saved." },
                    { "save_failed", "Save failed." },
                    { "solver_input_loaded", "Solver input loaded." },
                    { "solver_loaded_press_solve", "Result: Loaded input. Press Solve to calculate a solution." },
                    { "no_solver_uses_available", "No solver uses available.\nUse a Solver Ticket or earn more uses later." },
                    { "solver_unavailable", "Solver unavailable" },
                    { "no_free_solver_uses", "No free solver uses or solver tickets are available." },
                    { "solving", "Solving..." },
                    { "solver_status", "Solver status" },
                    { "free_solver_uses_today", "Free solver uses today" },
                    { "solver_not_connected", "Solver not connected" },
                    { "solver_timed_out", "The current solver timed out." },
                    { "solver_solution_not_found_valid", "This cube is valid, but the current solver could not find a solution." },
                    { "solution_not_found", "Solution not found" },
                    { "invalid_cube_state", "Invalid cube state" },
                    { "check_corner_edge_colors", "Please check corner and edge colors." },
                    { "no_solver_solution_available", "No solver solution available." },
                    { "no_moves_needed_cube_solved", "No moves needed. Cube is already solved." },
                    { "dev_solver_not_consumed", "Dev mode: solver use not consumed." },
                    { "solver_use_not_consumed", "Solver use not consumed." },
                    { "tickets", "Tickets" },
                    { "solver_ticket_used", "Solver ticket used." },
                    { "solution_found_no_use_consumed", "Solution found, but no solver use was consumed." },
                    { "failed", "Failed" },
                    { "solver_returned_no_result", "Solver returned no result." },
                    { "solution_found", "Solution found" },
                    { "moves_list", "Moves list" },
                    { "more", "more" },
                    { "please_check_cube_input", "Please check the cube input." },
                    { "code_label", "Code" },
                    { "check_color_counts", "Check color counts. Each color must appear 9 times." },
                    { "center_colors_unique", "Center colors must be unique." },
                    { "invalid_cube_state_unsolvable", "Invalid cube state. This cube cannot be solved from normal turns." },
                    { "solver_solution_not_found_stronger", "This cube is valid, but the current solver could not find a solution. A stronger solver engine is required for this pattern." },
                    { "solver_engine_not_connected", "Solver engine is not connected." },
                    { "solver_failed", "Solver failed." },
                    { "none_value", "(none)" },
                    { "filled", "Filled" },
                    { "ready", "Ready" },
                    { "check_input", "Check input" }
                    ,
                    { "solve_count", "Solve x {0}" },
                    { "completed", "Completed" },
                    { "no_world_records", "No world records yet." },
                    { "reward_claimed_title", "Reward Claimed!" },
                    { "solver_ticket_count", "Solver Ticket x{0}" },
                    { "solver_debug_saved", "Solver debug report copied and saved as the latest debug case." },
                    { "beginner_method", "Beginner Method" },
                    { "formula_practice", "Formula Practice" },
                    { "tutorial_playback", "Tutorial Playback" },
                    { "learn_hub_manual_desc", "Enter your cube and get a solution." },
                    { "learn_hub_basics_desc", "Understand faces, turns, and notation." },
                    { "learn_hub_beginner_desc", "Learn the 3x3 step by step." },
                    { "learn_hub_formulas_desc", "Practice common move patterns." },
                    { "learn_hub_playback_desc", "Watch guided face-turn demonstrations." },
                    { "learn_hub_practice_desc", "Practice freely without limits.\nNo hearts required." }
                    ,
                    { "demo", "Demo" },
                    { "learn_default_demo_guide", "This is a demo. Follow the lesson explanation." },
                    { "learn_white_bottom_guide", "White is kept on the bottom in this beginner method." },
                    { "learn_yellow_edge_cyan_slot", "Yellow marks the target edge; cyan marks the bottom slot." },
                    { "learn_yellow_corner_cyan_slot", "Yellow marks the target corner; cyan marks its first-layer slot." },
                    { "learn_keep_white_corner_slot", "Keep white on the bottom. Yellow marks the corner; cyan marks its slot." },
                    { "learn_prepared_pair_slot", "Yellow marks the prepared pair reference; cyan marks the F2L slot." },
                    { "learn_solved_layers_top_result", "Keep the solved layers underneath and watch the top-face result." },
                    { "learn_pattern_demo_only", "Pattern demo only; use it in the correct solving case." },
                    { "demo_type_move", "Move Demo" },
                    { "demo_type_pattern", "Pattern Demo - Not a full solving case" },
                    { "demo_type_right_trigger", "Guided Demo - Insert a right-side corner" },
                    { "demo_type_left_trigger", "Guided Demo - Insert a left-side corner" },
                    { "demo_type_sledgehammer", "Guided Demo - Insert a prepared F2L pair" },
                    { "demo_type_yellow_cross", "Guided Demo - Turn a yellow line into a cross" },
                    { "demo_type_right_algorithm", "Guided Demo - Complete the yellow face" },
                    { "demo_type_beginner_step", "Step Demo - Watch the target piece move into place" },
                    { "demo_type_beginner_multi", "Step-by-step Demo - Complete four white edges" },
                    { "demo_type_beginner_corner", "Case Demo - Insert white corners without breaking the cross" },
                    { "demo_type_beginner_second_layer", "Case Demo - Complete the second layer" },
                    { "demo_type_beginner_yellow_cross", "Pattern Demo - Build the yellow cross" },
                    { "demo_type_beginner_yellow_face", "Pattern Demo - Orient the yellow face" },
                    { "demo_type_beginner_last_corners", "Case Demo - Position the last-layer corners" },
                    { "demo_type_beginner_last_edges", "Case Demo - Position the final edges" },
                    { "demo_type_explanation", "Explanation Only" }
                }
            },
            {
                AppLanguage.Korean,
                new Dictionary<string, string>
                {
                    { "play", "\uD50C\uB808\uC774" },
                    { "quick_play", "\uC5F0\uC2B5" },
                    { "practice", "\uC5F0\uC2B5" },
                    { "ranking_challenge", "\uB7AD\uD0B9\u0020\uCC4C\uB9B0\uC9C0" },
                    { "stages", "\uC2A4\uD14C\uC774\uC9C0" },
                    { "target", "\uBAA9\uD45C" },
                    { "solver", "\uC194\uBC84" },
                    { "solver_learn", "\uC194\uBC84\u0020\u0026\u0020\uD559\uC2B5" },
                    { "records", "\uC6D4\uB4DC\u0020\uB808\uCF54\uB4DC" },
                    { "shop", "\uC0C1\uC810" },
                    { "rewards", "\uBCF4\uC0C1" },
                    { "coins", "\uCF54\uC778" },
                    { "gems", "\uC82C" },
                    { "buy", "\uAD6C\uB9E4" },
                    { "owned", "\uBCF4\uC720\u0020\uC911" },
                    { "not_enough_coins", "\uCF54\uC778\uC774\u0020\uBD80\uC871\uD569\uB2C8\uB2E4" },
                    { "daily_reward", "\uC77C\uC77C\u0020\uBCF4\uC0C1" },
                    { "claim", "\uBC1B\uAE30" },
                    { "claimed", "\uC218\uB839\u0020\uC644\uB8CC" },
                    { "ranking", "\uB7AD\uD0B9" },
                    { "settings", "\uC124\uC815" },
                    { "back", "\uB4A4\uB85C" },
                    { "home", "\uD648" },
                    { "retry", "\uB2E4\uC2DC\u0020\uC2DC\uB3C4" },
                    { "new_game", "\uC0C8\u0020\uAC8C\uC784" },
                    { "reset", "\uCD08\uAE30\uD654" },
                    { "time", "\uC2DC\uAC04" },
                    { "moves", "\uC774\uB3D9" },
                    { "continue", "\uACC4\uC18D" },
                    { "hint", "\uD78C\uD2B8" },
                    { "view", "\uBCF4\uAE30" },
                    { "solve", "\uD480\uAE30" },
                    { "drag", "\uB4DC\uB798\uADF8" },
                    { "keypad", "\uD0A4\uD328\uB4DC" },
                    { "undo", "\uB418\uB3CC\uB9AC\uAE30" },
                    { "help", "\uB3C4\uC6C0\uB9D0" },
                    { "close", "\uB2EB\uAE30" },
                    { "sound", "\uC0AC\uC6B4\uB4DC" },
                    { "vibration", "\uC9C4\uB3D9" },
                    { "push_notifications", "\uD478\uC2DC\u0020\uC54C\uB9BC" },
                    { "language", "\uC5B8\uC5B4" },
                    { "english", "English" },
                    { "korea", "Korea" },
                    { "coming_soon", "\uC900\uBE44\u0020\uC911" },
                    { "locked", "\uC7A0\uAE40" },
                    { "cleared", "\uD074\uB9AC\uC5B4" },
                    { "stars", "\uBCC4" },
                    { "difficulty", "\uB09C\uC774\uB3C4" },
                    { "move_limit", "\uC774\uB3D9\u0020\uC81C\uD55C" },
                    { "stage_clear", "\uC2A4\uD14C\uC774\uC9C0\u0020\uD074\uB9AC\uC5B4\u0021" },
                    { "stage_failed", "\uC774\uB3D9\u0020\uD69F\uC218\u0020\uCD08\uACFC" },
                    { "remaining_moves", "\uB0A8\uC740\u0020\uC774\uB3D9" },
                    { "next_stage", "\uB2E4\uC74C\u0020\uC2A4\uD14C\uC774\uC9C0" },
                    { "stage_list", "\uC2A4\uD14C\uC774\uC9C0\u0020\uBAA9\uB85D" },
                    { "best_moves", "\uCD5C\uACE0\u0020\uC774\uB3D9\u0020\uC218" },
                    { "best_time", "\uCD5C\uACE0\u0020\uAE30\uB85D" },
                    { "star_conditions_title", "\ubcc4\uc810 \ud074\ub9ac\uc5b4 \uc870\uac74" },
                    { "star_title_count", "\ubcc4 {0}\uac1c" },
                    { "star_title_one", "\ubcc4 {0}\uac1c" },
                    { "star_condition_3", "{0}\ud68c \uc774\ub0b4 \ud074\ub9ac\uc5b4\n\ub3c4\uc6c0 \uc544\uc774\ud15c \ubbf8\uc0ac\uc6a9" },
                    { "star_condition_2", "{0}\ud68c \uc774\ub0b4 \ud074\ub9ac\uc5b4\n\ub610\ub294 \ub3c4\uc6c0 \uc544\uc774\ud15c 1-2\uac1c \uc0ac\uc6a9 \ud6c4" },
                    { "star_condition_1", "{0}\ud68c \uc774\ub0b4 \ud074\ub9ac\uc5b4\n\ub610\ub294 \ucd94\uac00 \ub3c4\uc6c0 \uc544\uc774\ud15c \ud328\ub110\ud2f0 \ud6c4" },
                    { "start", "\uC2DC\uC791" },
                    { "no_records", "\uC544\uC9C1\u0020\uAE30\uB85D\uC774\u0020\uC5C6\uC2B5\uB2C8\uB2E4\u002E" },
                    { "purchased", "\uAD6C\uB9E4\uD588\uC2B5\uB2C8\uB2E4\u002E" },
                    { "equipped", "\uC7A5\uCC29\uD588\uC2B5\uB2C8\uB2E4\u002E" },
                    { "already_owned", "\uC774\uBBF8\u0020\uBCF4\uC720\u0020\uC911\uC785\uB2C8\uB2E4\u002E" },
                    { "not_enough_gems", "\uC82C\uC774\u0020\uBD80\uC871\uD569\uB2C8\uB2E4\u002E" },
                    { "hearts", "\uD558\uD2B8" },
                    { "uses_one_heart", "\uD558\uD2B8\u0020\u0031\uAC1C\u0020\uC0AC\uC6A9" },
                    { "not_enough_hearts", "\uD558\uD2B8\uAC00\u0020\uBD80\uC871\uD569\uB2C8\uB2E4" },
                    { "hearts_recharge", "\uD558\uD2B8\uB294\u0020\uC2DC\uAC04\uC774\u0020\uC9C0\uB098\uBA74\u0020\uCDA9\uC804\uB429\uB2C8\uB2E4\u002E" },
                    { "next_heart_in", "\uB2E4\uC74C\u0020\uD558\uD2B8\uAE4C\uC9C0" },
                    { "get_more_hearts", "\uC0C1\uC810\uC5D0\uC11C\u0020\uD558\uD2B8\uB97C\u0020\uB354\u0020\uBC1B\uC744\u0020\uC218\u0020\uC788\uC2B5\uB2C8\uB2E4\u002E" },
                    { "no_hearts_required", "\uD558\uD2B8\uAC00\u0020\uD544\uC694\u0020\uC5C6\uC2B5\uB2C8\uB2E4\u002E" },
                    { "go_to_shop", "\uC0C1\uC810\uC73C\uB85C\u0020\uC774\uB3D9" },
                    { "reward_claimed", "\uBCF4\uC0C1\uC744\u0020\uBC1B\uC558\uC2B5\uB2C8\uB2E4\u002E" },
                    { "reward", "보상" },
                    { "ad_not_ready", "\uAD11\uACE0\uAC00\u0020\uC544\uC9C1\u0020\uC900\uBE44\uB418\uC9C0\u0020\uC54A\uC558\uC2B5\uB2C8\uB2E4\u002E\u0020\uC7A0\uC2DC\u0020\uD6C4\u0020\uB2E4\uC2DC\u0020\uC2DC\uB3C4\uD574\uC8FC\uC138\uC694\u002E" },
                    { "ad_not_completed", "\uAD11\uACE0\uAC00\u0020\uC644\uB8CC\uB418\uC9C0\u0020\uC54A\uC558\uC2B5\uB2C8\uB2E4\u002E" },
                    { "ads_unavailable", "\uAD11\uACE0\uB97C\u0020\uC544\uC9C1\u0020\uC0AC\uC6A9\uD560\u0020\uC218\u0020\uC5C6\uC2B5\uB2C8\uB2E4\u002E" },
                    { "profile", "\uD504\uB85C\uD544" },
                    { "customize_experience", "\uD50C\uB808\uC774\u0020\uD658\uACBD\uC744\u0020\uC124\uC815\uD558\uC138\uC694" },
                    { "nickname", "\uB2C9\uB124\uC784" },
                    { "edit", "\uC218\uC815" },
                    { "google_play", "Google Play" },
                    { "connected", "\uC5F0\uACB0\uB428" },
                    { "connect", "\uC5F0\uACB0" },
                    { "not_connected", "\uC5F0\uACB0\u0020\uC548\u0020\uB428" },
                    { "on", "\uCF1C\uC9D0" },
                    { "off", "\uAEBC\uC9D0" },
                    { "change_nickname", "\uB2C9\uB124\uC784\u0020\uBCC0\uACBD" },
                    { "choose_avatar", "\uC544\uBC14\uD0C0\u0020\uC120\uD0DD" },
                    { "nickname_ticket_info", "\uB2C9\uB124\uC784\u0020\uBCC0\uACBD\uAD8C\u0020\u0031\uAC1C\u0020\uC0AC\uC6A9\\n\uB2C9\uB124\uC784\uC740\u0020\uD558\uB8E8\uC5D0\u0020\uD55C\u0020\uBC88\uB9CC\u0020\uBCC0\uACBD\uD560\u0020\uC218\u0020\uC788\uC2B5\uB2C8\uB2E4\u002E" },
                    { "cancel", "\uCDE8\uC18C" },
                    { "ok", "\uD655\uC778" },
                    { "nickname_placeholder", "\uB2C9\uB124\uC784" },
                    { "choose_language", "\uC5B8\uC5B4\u0020\uC120\uD0DD" },
                    { "language_changed", "\uC5B8\uC5B4\uAC00\u0020\uBCC0\uACBD\uB418\uC5C8\uC2B5\uB2C8\uB2E4\u002E" },
                    { "create_profile_first", "\uBA3C\uC800\u0020\uD504\uB85C\uD544\uC744\u0020\uB9CC\uB4E4\uC5B4\uC8FC\uC138\uC694\u002E" },
                    { "google_play_failed", "Google Play \uB85C\uADF8\uC778\uC5D0\u0020\uC2E4\uD328\uD588\uC2B5\uB2C8\uB2E4\u002E\u0020\uB2E4\uC2DC\u0020\uC2DC\uB3C4\uD574\uC8FC\uC138\uC694\u002E" },
                    { "google_play_connected", "Google Play\uAC00\u0020\uC5F0\uACB0\uB418\uC5C8\uC2B5\uB2C8\uB2E4\u002E" },
                    { "avatar_anytime", "\uC544\uBC14\uD0C0\uB294\u0020\uC5B8\uC81C\uB4E0\uC9C0\u0020\uBCC0\uACBD\uD560\u0020\uC218\u0020\uC788\uC2B5\uB2C8\uB2E4\u002E" },
                    { "avatar_changed", "\uC544\uBC14\uD0C0\uAC00\u0020\uBCC0\uACBD\uB418\uC5C8\uC2B5\uB2C8\uB2E4\u002E" },
                    { "avatar_changed_synced", "\uC544\uBC14\uD0C0\uAC00\u0020\uBCC0\uACBD\uB418\uACE0\u0020\uB3D9\uAE30\uD654\uB418\uC5C8\uC2B5\uB2C8\uB2E4\u002E" },
                    { "avatar_changed_local", "\uC544\uBC14\uD0C0\uAC00\u0020\uB85C\uCEEC\uC5D0\uC11C\u0020\uBCC0\uACBD\uB418\uC5C8\uC2B5\uB2C8\uB2E4\u002E\u0020\uC11C\uBC84\u0020\uB3D9\uAE30\uD654\u0020\uB300\uAE30\u0020\uC911\uC785\uB2C8\uB2E4\u002E" },
                    { "tickets_available", "\uBCF4\uC720\u0020\uBCC0\uACBD\uAD8C\u003A\u0020{0}" },
                    { "need_nickname_ticket", "\uB2C9\uB124\uC784\u0020\uBCC0\uACBD\uAD8C\uC774\u0020\uD544\uC694\uD569\uB2C8\uB2E4\u002E" }
                    ,
                    { "manual_solver", "\uc218\ub3d9 \uc194\ubc84" },
                    { "learn_basics", "\uae30\ucd08 \ubc30\uc6b0\uae30" },
                    { "solver_learn_title", "\uc194\ubc84 & \ud559\uc2b5" },
                    { "solver_learn_subtitle", "\uc194\ubc84 \ub610\ub294 \ud559\uc2b5 \uba54\ub274\ub97c \uc120\ud0dd\ud558\uc138\uc694." },
                    { "solver_instruction", "색상을 선택한 뒤 스티커를 입력하세요." },
                    { "previous", "이전" },
                    { "next", "다음" },
                    { "validate", "검사" },
                    { "reset_solved", "완성 상태로 초기화" },
                    { "clear", "지우기" },
                    { "save", "저장" },
                    { "load", "불러오기" },
                    { "play_3d", "3D 보기" },
                    { "debug", "디버그" },
                    { "open", "\uc5f4\uae30" },
                    { "lessons", "\uac15\uc758" },
                    { "lesson", "\uac15\uc758" },
                    { "previous_edge", "\uc774\uc804 \uc5e3\uc9c0" },
                    { "next_edge", "\ub2e4\uc74c \uc5e3\uc9c0" },
                    { "previous_case", "\uc774\uc804 \uc0ac\ub840" },
                    { "next_case", "\ub2e4\uc74c \uc0ac\ub840" },
                    { "mark_complete", "\uc644\ub8cc \ud45c\uc2dc" },
                    { "play_demo", "3D \ub370\ubaa8 \uc7ac\uc0dd" },
                    { "back_to_lessons", "\uac15\uc758 \ubaa9\ub85d\uc73c\ub85c" },
                    { "learn_3d_demo", "\ud559\uc2b5 3D \ub370\ubaa8" },
                    { "learn_3d_demo_subtitle", "\ub3d9\uc791\uc744 \ubcf4\ub294 \ub3d9\uc548 \uc55e\uba74, \uc717\uba74, \uc624\ub978\ucabd\uba74 \uae30\uc900\uc744 \uc720\uc9c0\ud558\uc138\uc694." },
                    { "lesson_completed", "\uac15\uc758\ub97c \uc644\ub8cc\ud588\uc2b5\ub2c8\ub2e4." },
                    { "lesson_unavailable", "\uac15\uc758\ub97c \uc0ac\uc6a9\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4" },
                    { "lesson_data_unavailable", "\uac15\uc758 \ub370\uc774\ud130\ub97c \uc0ac\uc6a9\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4." },
                    { "no_lesson_category", "\uc0ac\uc6a9 \uac00\ub2a5\ud55c \uac15\uc758 \uce74\ud14c\uace0\ub9ac\uac00 \uc5c6\uc2b5\ub2c8\ub2e4." },
                    { "key_points", "\ud575\uc2ec \ud3ec\uc778\ud2b8" },
                    { "moves_label", "\ub3d9\uc791" },
                    { "demo_type_label", "\ub370\ubaa8 \uc885\ub958" },
                    { "demo_purpose_label", "\ub370\ubaa8 \ubaa9\uc801" },
                    { "demo_goal_label", "\ub370\ubaa8 \ubaa9\ud45c" },
                    { "target_piece_label", "\ubaa9\ud45c \uc870\uac01" },
                    { "target_slot_label", "\ubaa9\ud45c \uc2ac\ub86f" },
                    { "no_3d_demo", "\uc774 \uac15\uc758\uc5d0\ub294 3D \ub370\ubaa8\uac00 \uc5c6\uc2b5\ub2c8\ub2e4." },
                    { "no_3d_demo_yet", "\uc774 \uac15\uc758\uc5d0\ub294 \uc544\uc9c1 3D \ub370\ubaa8\uac00 \uc5c6\uc2b5\ub2c8\ub2e4." },
                    { "learn_more_later", "\ub354 \ub9ce\uc740 \uc548\ub0b4 \uc0ac\ub840\ub294 \ub2e4\uc74c Learn \uc5c5\ub370\uc774\ud2b8\uc5d0\uc11c \ud655\uc7a5\ub429\ub2c8\ub2e4." },
                    { "target_pattern", "목표 패턴" },
                    { "match_this_cube", "이 큐브와 맞추세요." },
                    { "view_target", "목표 보기" },
                    { "continue_plus_moves", "계속 +{0}" },
                    { "move_plus", "+{0} 이동" },
                    { "force_clear", "강제 클리어" },
                    { "out_of_moves_ad", "이동 횟수 초과\n광고 보고 +{0} 이동 얻기\n{1}/{2} 사용" },
                    { "daily_rewards_title", "일일 보상" },
                    { "daily_rewards_subtitle", "오늘의 보상을 받고 솔버 티켓 3개를 획득하세요!" },
                    { "day_label", "{0}일차" },
                    { "solver_tickets", "솔버 티켓" },
                    { "world_records_title", "월드 레코드" },
                    { "world_records_subtitle", "가장 많은 스테이지를 클리어한 플레이어를 확인하세요." },
                    { "rank", "순위" },
                    { "player", "플레이어" },
                    { "stage", "스테이지" }
                    ,
                    { "tutorial_mode", "튜토리얼 모드" },
                    { "normal_mode", "노말 모드" },
                    { "hard_mode", "하드 모드" },
                    { "infinity_mode", "인피니티 모드" },
                    { "tutorial_mode_desc", "초급 스테이지를 클리어하고 별을 모으세요." },
                    { "normal_mode_desc", "스테이지를 클리어하고 별을 모으세요." },
                    { "hard_mode_desc", "목표 스테이지를 맞추고 별을 모으세요." },
                    { "infinity_mode_desc", "끝없는 진행 방식의 혼합 스테이지입니다." },
                    { "select_block", "블록 선택" },
                    { "choose_block", "확인할 블록을 선택하세요." },
                    { "block_rewards", "블록 보상" },
                    { "block_label", "블록 {0}" },
                    { "block_multiline", "블록\n{0}" },
                    { "stages_range", "스테이지 {0} - {1}" },
                    { "complete_stages_rewards", "스테이지를 완료하고 별을 모아 멋진 보상을 받으세요!" },
                    { "locked_label", "잠김" },
                    { "solver_learn_hint", "Solver & Learn 메뉴에서 면, 회전, 표기법을 배워보세요." },
                    { "solver_result_not_solved", "결과: 아직 풀이 전입니다." },
                    { "invalid_cube_input", "잘못된 큐브 입력" },
                    { "cube_input_valid", "큐브 입력이 올바릅니다." },
                    { "status_label", "상태" },
                    { "validation_passed", "검사 통과" },
                    { "ready_to_solve", "풀이 준비 완료" },
                    { "invalid_cube", "잘못된 큐브" },
                    { "reset_to_solved_cube", "완성된 큐브 상태로 초기화했습니다." },
                    { "cube_already_solved", "이미 맞춰진 큐브입니다" },
                    { "solution_label", "풀이" },
                    { "no_moves_needed", "필요한 동작 없음" },
                    { "input_cleared", "입력을 지웠습니다." },
                    { "solver_input_saved", "솔버 입력을 저장했습니다." },
                    { "save_failed", "저장에 실패했습니다." },
                    { "solver_input_loaded", "솔버 입력을 불러왔습니다." },
                    { "solver_loaded_press_solve", "결과: 입력을 불러왔습니다. Solve를 눌러 풀이를 계산하세요." },
                    { "no_solver_uses_available", "사용 가능한 솔버 횟수가 없습니다.\n솔버 티켓을 사용하거나 나중에 다시 이용하세요." },
                    { "solver_unavailable", "솔버 사용 불가" },
                    { "no_free_solver_uses", "무료 솔버 횟수 또는 솔버 티켓이 없습니다." },
                    { "solving", "풀이 중..." },
                    { "solver_status", "솔버 상태" },
                    { "free_solver_uses_today", "오늘 남은 무료 솔버 횟수" },
                    { "solver_not_connected", "솔버가 연결되지 않음" },
                    { "solver_timed_out", "현재 솔버가 시간 초과되었습니다." },
                    { "solver_solution_not_found_valid", "큐브는 올바르지만 현재 솔버가 풀이를 찾지 못했습니다." },
                    { "solution_not_found", "풀이를 찾지 못함" },
                    { "invalid_cube_state", "잘못된 큐브 상태" },
                    { "check_corner_edge_colors", "코너와 엣지 색상을 확인하세요." },
                    { "no_solver_solution_available", "사용 가능한 솔버 풀이가 없습니다." },
                    { "no_moves_needed_cube_solved", "필요한 동작이 없습니다. 이미 맞춰진 큐브입니다." },
                    { "dev_solver_not_consumed", "개발 모드: 솔버 사용 횟수를 차감하지 않았습니다." },
                    { "solver_use_not_consumed", "솔버 사용 횟수를 차감하지 않았습니다." },
                    { "tickets", "티켓" },
                    { "solver_ticket_used", "솔버 티켓을 사용했습니다." },
                    { "solution_found_no_use_consumed", "풀이를 찾았지만 솔버 사용 횟수는 차감되지 않았습니다." },
                    { "failed", "실패" },
                    { "solver_returned_no_result", "솔버가 결과를 반환하지 않았습니다." },
                    { "solution_found", "풀이 찾음" },
                    { "moves_list", "동작 목록" },
                    { "more", "개 더" },
                    { "please_check_cube_input", "큐브 입력을 확인하세요." },
                    { "code_label", "코드" },
                    { "check_color_counts", "색상 개수를 확인하세요. 각 색상은 9개씩 있어야 합니다." },
                    { "center_colors_unique", "센터 색상은 서로 달라야 합니다." },
                    { "invalid_cube_state_unsolvable", "잘못된 큐브 상태입니다. 정상적인 회전으로는 풀 수 없습니다." },
                    { "solver_solution_not_found_stronger", "큐브는 올바르지만 현재 솔버가 풀이를 찾지 못했습니다. 이 패턴에는 더 강한 솔버 엔진이 필요합니다." },
                    { "solver_engine_not_connected", "솔버 엔진이 연결되지 않았습니다." },
                    { "solver_failed", "솔버 실패." },
                    { "none_value", "(없음)" },
                    { "filled", "입력됨" },
                    { "ready", "준비됨" },
                    { "check_input", "입력 확인" }
                    ,
                    { "solve_count", "솔브 x {0}" },
                    { "completed", "완료됨" },
                    { "no_world_records", "아직 월드 레코드가 없습니다." },
                    { "reward_claimed_title", "보상 수령 완료!" },
                    { "solver_ticket_count", "솔버 티켓 x{0}" },
                    { "solver_debug_saved", "솔버 디버그 리포트를 복사하고 최신 디버그 케이스로 저장했습니다." },
                    { "beginner_method", "\ucd08\uae09 \uacf5\uc2dd" },
                    { "formula_practice", "\uacf5\uc2dd \uc5f0\uc2b5" },
                    { "tutorial_playback", "\ud29c\ud1a0\ub9ac\uc5bc \uc7ac\uc0dd" },
                    { "learn_hub_manual_desc", "\ud050\ube0c \uc0c1\ud0dc\ub97c \uc785\ub825\ud558\uace0 \ud480\uc774\ub97c \ud655\uc778\ud558\uc138\uc694." },
                    { "learn_hub_basics_desc", "\uba74, \ud68c\uc804, \ud45c\uae30\ubc95\uc744 \uc774\ud574\ud558\uc138\uc694." },
                    { "learn_hub_beginner_desc", "3x3 \ud050\ube0c\ub97c \ub2e8\uacc4\ubcc4\ub85c \ubc30\uc6cc\ubcf4\uc138\uc694." },
                    { "learn_hub_formulas_desc", "\uc790\uc8fc \uc4f0\ub294 \ub3d9\uc791 \ud328\ud134\uc744 \uc5f0\uc2b5\ud558\uc138\uc694." },
                    { "learn_hub_playback_desc", "\uc548\ub0b4\uac00 \uc788\ub294 \uba74 \ud68c\uc804 \ub370\ubaa8\ub97c \ubcf4\uc138\uc694." },
                    { "learn_hub_practice_desc", "\uc81c\ud55c \uc5c6\uc774 \uc790\uc720\ub86d\uac8c \uc5f0\uc2b5\ud558\uc138\uc694.\n\ud558\ud2b8\uac00 \ud544\uc694 \uc5c6\uc2b5\ub2c8\ub2e4." },
                    { "demo", "\ub370\ubaa8" },
                    { "learn_default_demo_guide", "\ub370\ubaa8\uc785\ub2c8\ub2e4. \uac15\uc758 \uc124\uba85\uc744 \ub530\ub77c\uac00\uc138\uc694." },
                    { "learn_white_bottom_guide", "\uc774 \ucd08\uae09 \ubc29\uc2dd\uc5d0\uc11c\ub294 \ud770\uc0c9\uc744 \uc544\ub798\uc5d0 \ub461\ub2c8\ub2e4." },
                    { "learn_yellow_edge_cyan_slot", "\ub178\ub780\uc0c9\uc740 \ubaa9\ud45c \uc5e3\uc9c0, \ud558\ub298\uc0c9\uc740 \uc544\ub798 \uc2ac\ub86f\uc744 \ud45c\uc2dc\ud569\ub2c8\ub2e4." },
                    { "learn_yellow_corner_cyan_slot", "\ub178\ub780\uc0c9\uc740 \ubaa9\ud45c \ucf54\ub108, \ud558\ub298\uc0c9\uc740 1\uce35 \uc2ac\ub86f\uc744 \ud45c\uc2dc\ud569\ub2c8\ub2e4." },
                    { "learn_keep_white_corner_slot", "\ud770\uc0c9\uc744 \uc544\ub798\uc5d0 \ub450\uc138\uc694. \ub178\ub780\uc0c9\uc740 \ucf54\ub108, \ud558\ub298\uc0c9\uc740 \uc2ac\ub86f\uc744 \ud45c\uc2dc\ud569\ub2c8\ub2e4." },
                    { "learn_prepared_pair_slot", "\ub178\ub780\uc0c9\uc740 \uc900\ube44\ub41c \ud398\uc5b4 \uae30\uc900, \ud558\ub298\uc0c9\uc740 F2L \uc2ac\ub86f\uc744 \ud45c\uc2dc\ud569\ub2c8\ub2e4." },
                    { "learn_solved_layers_top_result", "\ub9de\ucdb0\uc9c4 \uce35\uc744 \uc544\ub798\uc5d0 \ub450\uace0 \uc717\uba74 \uacb0\uacfc\ub97c \ud655\uc778\ud558\uc138\uc694." },
                    { "learn_pattern_demo_only", "\ud328\ud134 \ub370\ubaa8\uc785\ub2c8\ub2e4. \uc62c\ubc14\ub978 \uc0c1\ud669\uc5d0\uc11c \uc0ac\uc6a9\ud558\uc138\uc694." },
                    { "demo_type_move", "\ub3d9\uc791 \ub370\ubaa8" },
                    { "demo_type_pattern", "\ud328\ud134 \ub370\ubaa8 - \uc804\uccb4 \ud480\uc774 \uc0ac\ub840 \uc544\ub2d8" },
                    { "demo_type_right_trigger", "\uc548\ub0b4 \ub370\ubaa8 - \uc624\ub978\ucabd \ucf54\ub108 \uc0bd\uc785" },
                    { "demo_type_left_trigger", "\uc548\ub0b4 \ub370\ubaa8 - \uc67c\ucabd \ucf54\ub108 \uc0bd\uc785" },
                    { "demo_type_sledgehammer", "\uc548\ub0b4 \ub370\ubaa8 - \uc900\ube44\ub41c F2L \ud398\uc5b4 \uc0bd\uc785" },
                    { "demo_type_yellow_cross", "\uc548\ub0b4 \ub370\ubaa8 - \ub178\ub780 \ub77c\uc778\uc744 \uc2ed\uc790\ub85c \ub9cc\ub4e4\uae30" },
                    { "demo_type_right_algorithm", "\uc548\ub0b4 \ub370\ubaa8 - \ub178\ub780 \uba74 \uc644\uc131" },
                    { "demo_type_beginner_step", "\ub2e8\uacc4 \ub370\ubaa8 - \ubaa9\ud45c \uc870\uac01\uc744 \uc81c\uc790\ub9ac\ub85c \uc774\ub3d9" },
                    { "demo_type_beginner_multi", "\ub2e8\uacc4\ubcc4 \ub370\ubaa8 - \ud770\uc0c9 \uc5e3\uc9c0 4\uac1c \uc644\uc131" },
                    { "demo_type_beginner_corner", "\uc0ac\ub840 \ub370\ubaa8 - \uc2ed\uc790\ub97c \uae68\uc9c0 \uc54a\uace0 \ud770\uc0c9 \ucf54\ub108 \uc0bd\uc785" },
                    { "demo_type_beginner_second_layer", "\uc0ac\ub840 \ub370\ubaa8 - \ub450 \ubc88\uc9f8 \uce35 \uc644\uc131" },
                    { "demo_type_beginner_yellow_cross", "\ud328\ud134 \ub370\ubaa8 - \ub178\ub780 \uc2ed\uc790 \ub9cc\ub4e4\uae30" },
                    { "demo_type_beginner_yellow_face", "\ud328\ud134 \ub370\ubaa8 - \ub178\ub780 \uba74 \ubc29\ud5a5 \ub9de\ucd94\uae30" },
                    { "demo_type_beginner_last_corners", "\uc0ac\ub840 \ub370\ubaa8 - \ub9c8\uc9c0\ub9c9 \uce35 \ucf54\ub108 \uc704\uce58 \ub9de\ucd94\uae30" },
                    { "demo_type_beginner_last_edges", "\uc0ac\ub840 \ub370\ubaa8 - \ub9c8\uc9c0\ub9c9 \uc5e3\uc9c0 \uc704\uce58 \ub9de\ucd94\uae30" },
                    { "demo_type_explanation", "\uc124\uba85 \uc804\uc6a9" }
                }
            }
        };

        private void Awake()
        {
            if (Instance != null && Instance != this)
            {
                Destroy(gameObject);
                return;
            }

            Instance = this;
            DontDestroyOnLoad(gameObject);
        }

        public void SetLanguage(AppLanguage language)
        {
            CurrentLanguage = language;
        }

        public void SetLanguageFromCode(string languageCode)
        {
            CurrentLanguage = string.Equals(languageCode, "ko", StringComparison.OrdinalIgnoreCase)
                ? AppLanguage.Korean
                : AppLanguage.English;
        }

        public static string ToLanguageCode(AppLanguage language)
        {
            return language == AppLanguage.Korean ? "ko" : "en";
        }

        public string GetLanguageDisplayName(AppLanguage language)
        {
            return language == AppLanguage.Korean ? GetText("korea") : GetText("english");
        }

        public string GetText(string key)
        {
            if (localizedText.TryGetValue(CurrentLanguage, out Dictionary<string, string> languageTable) &&
                languageTable.TryGetValue(key, out string value))
            {
                return value;
            }

            if (localizedText[AppLanguage.English].TryGetValue(key, out string fallback))
            {
                return fallback;
            }

            return key;
        }
    }
}
